### ISSUE TITLE
buildNativeImage FAILED

### ISSUE THREAD

**Issue by letrungtrung** [ayltai/spring-graalvm-native-plugin#4] opened 2020-07-22 08:00 UTC
After setup Gradle project like your sample, I run take 'buildNativeImage' and  receiving fail logs below. 
The version I used: id 'com.github.ayltai.spring-graalvm-native-plugin' version '1.0.7'

> Task :processResources
> Task :classes
> Task :bootJar SKIPPED
> Task :buildNativeImage FAILED
3 actionable tasks: 3 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildNativeImage'.
> /Users/letrungtrung/Documents/workspace/server/hotit/chat-websocket-server/build/libs/missle-gateway-2020.3.1.jar (No such file or directory)
   > /Users/letrungtrung/Documents/workspace/server/hotit/chat-websocket-server/build/libs/missle-gateway-2020.3.1.jar (No such file or directory)

**Comment by ayltai** [comment] 2020-07-22 08:13
This is impossible for me to find what the root cause is. Can you provide me with your `build.gradle` so that I can check what Jar files should be extracted and referenced by the native build process.

**Comment by letrungtrung** [comment] 2020-07-23 15:40
> This is impossible for me to find what the root cause is. Can you provide me with your `build.gradle` so that I can check what Jar files should be extracted and referenced by the native build process.

I tested on your sample, it's ok, maybe some libs not support to build that, i will check it.
Finally, I have a question: files in resources folder, where they will be attached after building native-image?
Thanks for your great job. I appreciate that

**Comment by letrungtrung** [comment] 2020-07-23 15:46
Warning: class initialization of class org.springframework.boot.validation.MessageInterpolatorFactory failed with exception java.lang.NoClassDefFoundError: javax/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.validation.MessageInterpolatorFactory to explicitly request delayed initialization of this class.

When i build your sample, i received above message. How to add --initialize-at-run-time in configuration  of nativeImage{}. I looked at it from your document, but still not found. Please help me

**Comment by ayltai** [comment] 2020-07-23 15:58
> I tested on your sample, it's ok, maybe some libs not support to build that, i will check it.
> Finally, I have a question: files in resources folder, where they will be attached after building native-image?
> Thanks for your great job. I appreciate that
It's transparent to developers. You don't need to care for that. Just use your resources as you would do with JVM. GraalVM will handle it for you.
If you want to learn more, please read the official documentation (https://www.graalvm.org/docs/reference-manual/native-image/). This is just a Gradle plugin which wraps some of the features provided by GraalVM.

**Comment by ayltai** [comment] 2020-07-23 16:01
> Warning: class initialization of class org.springframework.boot.validation.MessageInterpolatorFactory failed with exception java.lang.NoClassDefFoundError: javax/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.validation.MessageInterpolatorFactory to explicitly request delayed initialization of this class.
> 
> When i build your sample, i received above message. How to add --initialize-at-run-time in configuration of nativeImage{}. I looked at it from your document, but still not found. Please help me

You may not need to handle this because it is a warning, not an error. Spring Boot uses reflection to invoke classes if they are included in your dependencies. If not, Spring Boot may not use it. So, did you run your native image after building to see if it runs fine?

**Comment by ayltai** [comment] 2020-07-23 16:06
I'm closing this issue as this is not related to this project. Please refer to the official [documentation](https://www.graalvm.org/docs/) for questions related to GraalVM.

**Closed by ayltai** 2020-07-23 16:06 UTC
Labels: question
