### ISSUE TITLE
macOS build error (Collecting native-compiler info with '/usr/bin/cc -v ' failed)

### ISSUE THREAD

**Issue by vitalyster** [ayltai/spring-graalvm-native-plugin#44] opened 2020-12-09 08:42 UTC
**Things to check before reporting a bug**

- [x] I have searched [GraalVM GitHub repository](https://github.com/oracle/graal/issues) and could not find a similar issue 
- [x] I have searched [Spring experimental GraalVM Native project](https://github.com/spring-projects-experimental/spring-graalvm-native/issues) and could not find a similar issue
- [x] I have attached a sample project so that the issue can be reproduced on other computers

**Describe the bug**

build failed with:
```
Error: Collecting native-compiler info with '/usr/bin/cc -v ' failed
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
com.oracle.svm.core.util.UserError$UserException: Collecting native-compiler info with '/usr/bin/cc -v ' failed
To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
```

**To Reproduce**

```
./gradlew buildNativeImage
```

**Expected behavior**

image should be built

**Screenshots**

-
**Desktop (please complete the following information):**

 - OS: macOS
 - Version 11.0.1

**Comment by ayltai** [comment] 2020-12-09 08:47
I believe this is a duplicate of #33 
I will work on it (when I have time)

**Closed by ayltai** 2020-12-09 08:47 UTC
Labels: bug

**Comment by artemptushkin** [comment] 2020-12-09 08:58
@vitalyster could you do this with `--stacktrace --info` and print log here? It depends on the exact error

**Comment by vitalyster** [comment] 2020-12-09 09:27
`disableToolchainChecking   = true` configuration option give me the same result as in #33

**Comment by artemptushkin** [comment] 2020-12-09 09:54
1
